tag_prefix = "v"
from_latest_tag = true
ignore_merge_commits = false
ignore_fixup_commits = false
disable_changelog = true
disable_bump_commit = true
branch_whitelist = ["main"]
skip_ci = "[skip ci]"
skip_untracked = false
pre_bump_hooks = []
post_bump_hooks = ["git push origin {{version_tag}}"]

[git_hooks]

[commit_types]
feat = { changelog_title = "Features", order = 1 }
fix = { changelog_title = "Bug Fixes", order = 2 }
perf = { changelog_title = "Performance Improvements", order = 3, bump_level = "Patch" }
docs = { changelog_title = "Documentation", order = 4 }
build = { changelog_title = "Dev + Maintenance", order = 5, bump_level = "Patch" }
ci = { changelog_title = "Dev + Maintenance", order = 5 }
test = { changelog_title = "Dev + Maintenance", order = 5 }
chore = { changelog_title = "Dev + Maintenance", order = 5 }
style = { changelog_title = "Dev + Maintenance", order = 5 }
refactor = { changelog_title = "Dev + Maintenance", order = 5, bump_level = "Patch" }
# The following commit types should be omitted from the changelog
revert = { changelog_title = "Revert", omit_from_changelog = true }

[changelog]
path = "CHANGELOG.md"
template = ".cog/changelog-template.tera"
remote = "github.com"
owner = "windexvalence"
repository = "plastered"
authors = [{ username = "windexvalence", signature = "windexvalence" }]

[bump_profiles]
