LASTFM_API_KEY_ENV_VAR_NAME = "LASTFM_API_KEY"

# TODO: determine if lastfm / mb waits are appropriate
SECONDS_BETWEEN_RED_API_CALLS = 5
SECONDS_BETWEEN_LASTFM_API_CALLS = 2
SECONDS_BETWEEN_MUSICBRAINZ_API_CALLS = 1

MAX_RED_API_RETRIES = 3
MAX_LASTFM_API_RETRIES = 3
MAX_MBID_API_RETRIES = 3

